---
- name: Setup the server host Virtual network
  hosts: serverhost
  roles:
    - r1_checkhostnetwork
    - r1_createVMs
  become: yes
  become_user: root

- name: Register the undercloud
  hosts: osp8-undercloud
  roles:
    - r2_registerundercloud
  become: yes
  become_user: root

- name: Configure the undercloud
  hosts: osp8-undercloud
  roles:
    - r3_deploy_undercloud 
    - r4_configureovercloud
    - r5_deploy_overcloud
  remote_user: stack

