---
- name: test conditions
  hosts: osp8-undercloud
  remote_user: stack
  tasks:
  - name: Find the file
    find: paths=/home/stack/
    register: find_undercloud_log
        
  - name: Find if Undercloud is successfully completed
    vars:
      undercloud_log_file: "/home/stack/undercloud_install_initial_install.log"
      success_rslt: "END return value: 0"
    shell: grep "{{ success_rslt }}" {{ undercloud_log_file }}
    register: Find_rslt
    ignore_errors: true            

  - debug: msg=" FOUND "
    

  - name: Verify bootif-fix service exist
    shell: systemctl -l |grep bootif-fix
    register: bootiffix_rslt
    ignore_errors: true

  - debug: msg=" bootif-fix FOUND "
    when: bootiffix_rslt is defined or Find_rslt.rc == 0 

  - block:
    - name: fix - set the ironic power_wait to 12
      lineinfile: dest=/etc/ironic/ironic.conf line="power_wait=12"
      register: fix_found
    - debug: var=fix_found
      when: fix_found.changed
    become: yes
    become_user: root

  - name: test ceph in overcloud
    debug: msg={{ overcloudnodes }}
    when: '"ceph" in "{{ overcloudnodes }}"'
#    debug: var=find_undercloud_log.files
#    when: find_undercloud_log.files is defined and {{ undercloud_log_file }} in find_undercloud_log.files


#    when: undercloud_log.find('{{ sucess_rslt }}')

#    when: "'{{sucess_rslt}}' in '{{undercloud_log}}'"




