---
- debug: var=item
#- debug: var=hostvars[item]
- debug: msg="image path = {{ hostvars[item].disk.path }}/{{ item }}.qcow2"

- name: Creating the overcloud images disk
  command: qemu-img create -f qcow2 -o preallocation=metadata {{ hostvars[item].disk.path }}/{{ item }}.qcow2 {{ hostvars[item].disk.size }}G

- name: Creating the overcloud osd disk
  command: qemu-img create -f qcow2 -o preallocation=metadata {{ hostvars[item].disk.path }}/{{ item }}-osd.qcow2 {{ hostvars[item].osd.size }}G
  when: '"ceph" in item'

- name: test deploy
  template:
    src: createovercloudxml.j2
    dest: /tmp/{{ item }}.sh
    mode: 0755

- name: Run the deploy script
  shell: /bin/bash /tmp/{{ item }}.sh


