---
##########################################
##  
## Create user stack
##
- name: Create stack user with ssh-key
  user: name=stack state=present generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa password={{ hostvars['osp10-undercloud'].undercloud_passwd |password_hash('sha512') }} groups=libvirtd
  register: create_stack_rc

- name: Add stack user to the sudoers
  action: 'lineinfile dest=/etc/sudoers.d/stack state=present create=yes regexp="stack .*" line="stack ALL=(ALL) NOPASSWD: ALL"'
  when: create_stack_rc.changed

- name: Ensure /etc/sudoers.d/stack file has correct permissions
  action: file path=/etc/sudoers.d/stack mode=0440 state=file owner=root group=root
#  when: create_stack_rc.changed

#- name: Generate the undercloud root key
#  shell: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@{{ hostvars['osp10-undercloud'].net.ip }} 'cat /dev/zero | ssh-keygen -b 2048 -q -N ""'
#  when: create_stack_rc.changed
#  ignore_errors: yes  

# Verify the rhel73 image exist and it has the good size
- find: paths="{{ image_path }}" recurse=no patterns="rhel73-guest.qcow2" size="{{ image_size }}"
  register: file_to_copy

- name: Copy the default rhel 7.3 image if doesnt exist
  copy:
    src: "rhel73-guest.qcow2"
    dest: "{{ image_path }}" 
    mode: 0755
  when: not file_to_copy.matched

######################################
#
#  Modifying the undercloud image
#  1) Remove cloud-init
#  2) Set root passwword
#  3) Create eth1 interface
#  4) Set static IP
#  5) Create the authority file for root user
#  6) Add stack user and provide key 

# Verify the undercloud image exist and it has the good size
#- find: paths="{{ image_path }}" recurse=no patterns="{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2" size="{{ hostvars['osp10-undercloud'].undercloud_image_size }}"
- name: Verify if {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 exist
  find: paths="{{ image_path }}" recurse=yes patterns="osp10-undercloud.qcow2" size="{{ hostvars['osp10-undercloud'].undercloud_image_size }}"
  register: image_to_create

# Create the undercloud image
- name: Creating the undercloud image
  command: /usr/bin/qemu-img  create -f qcow2 -b {{ image_path }}{{image_rhel7_guest}} {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2
  when: not image_to_create.matched

# Accelerate the boot process - remove cloud-init
- name: Accelerate the boot process - remove cloud-init
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'yum remove cloud-init* -y'
  when: not image_to_create.matched

# Set root passwd - Redhat01
- name: Set root passwd - Redhat01
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --root-password password:Redhat01
  when: not image_to_create.matched

# Undercloud machine has an interface on our default network, so create an interface config file for eth1:
- name: Create an interface config file for eth1
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'touch /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "DEVICE=eth1" >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "ONBOOT=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  when: not image_to_create.matched

# Disable eth0 interface (provisioning)
- name: Disable eth0 interface
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'sed -i s/ONBOOT=.*/ONBOOT=no/g /etc/sysconfig/network-scripts/ifcfg-eth0'
  when: not image_to_create.matched

- name: Set the IP of the eth1 interface
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'echo "IPADDR={{ hostvars['osp10-undercloud'].net.ip }}" >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "NETMASK={{ hostvars['osp10-undercloud'].net.ntmk }}" >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "GATEWAY={{ hostvars['osp10-undercloud'].net.gtw }}" >> /etc/sysconfig/network-scripts/ifcfg-eth1 && echo "DNS1={{ hostvars['osp10-undercloud'].net.dns1 }}" >> /etc/sysconfig/network-scripts/ifcfg-eth1'
  when: not image_to_create.matched

- name: Getting the root public key
  shell: cat ~/.ssh/id_rsa.pub
  register: root_pubkey

- name: Create the authority file
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'mkdir /root/.ssh;chmod 700 /root/.ssh;echo "{{ root_pubkey.stdout }}" >> /root/.ssh/authorized_keys;chmod 600 /root/.ssh/authorized_keys;touch /.autorelabel'
  when: not image_to_create.matched

# Add the stack user to the image

- name: Create the undercloud stack keys path
  shell: mkdir -p /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}
  ignore_errors: yes  
  when: not image_to_create.matched

- name: Create the undercloud keys
  shell: cat /dev/zero | ssh-keygen -b 2048 -f /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey -q -N ""
  ignore_errors: yes
  when: not image_to_create.matched

- name: get the undercloud priv key
  shell: cat /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey
  register: uc_stack_privkey
  when: not image_to_create.matched

- name: get the undercloud pub key
  shell: cat /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey.pub
  register: uc_stack_pubkey
  when: not image_to_create.matched

- name: Change key files permission
  shell: chmod 777 -R /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/; chown -R stack:stack /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}
  when: not image_to_create.matched

- name: get the host server stack pub key
  shell: cat /home/stack/.ssh/id_rsa.pub
  register: hs_stack_pubkey
  when: not image_to_create.matched

- debug: msg="src=/tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey.pub"
- name: Add privte undercloud stack key to host server stack auth key
  #  copy: src=/tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey.pub dest=/home/stack/.ssh/authorized_keys owner=stack group=stack mode=0600 remote_src=False
  #  copy: src=/tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey.pub dest=/home/stack/.ssh/authorized_keys owner=stack group=stack mode=0600 remote_src=True
  shell: cp /tmp/{{ hostvars['osp10-undercloud'].undercloud_name }}/stackkey.pub /home/stack/.ssh/authorized_keys;chown stack:stack /home/stack/.ssh/authorized_keys; chmod 0600 /home/stack/.ssh/authorized_keys
  when: not image_to_create.matched


- name: Add stack user to the image
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'useradd stack;echo "{{ stack_passwd }}"| passwd --stdin stack'
  when: not image_to_create.matched

- name: Add stack keys to the image
  command: /usr/bin/virt-customize -a {{ image_path }}{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2 --run-command 'mkdir /home/stack/.ssh;chmod 700 /home/stack/.ssh;echo "{{ uc_stack_privkey.stdout }}">/home/stack/.ssh/id_rsa;echo "{{ uc_stack_pubkey.stdout }}">/home/stack/.ssh/id_rsa.pub;echo "{{ root_pubkey.stdout }}" >> /home/stack/.ssh/authorized_keys;chmod 600 -R /home/stack/.ssh/*;echo "{{ hs_stack_pubkey.stdout }}" >> /home/stack/.ssh/authorized_keys;chown stack:stack -R /home/stack/.ssh'
  when: not image_to_create.matched

#########################################################################
#
#  Creating the undercloud VM
#  Note: "Sleep 4" => Since the undercloud image has "/.autorelabel" file, 
#                     it's better to pause the deployment 
#                     

- name: get list of vms
  virt: command=list_vms
  register: virt_vms

# Deploy undercloud VM
- name: Deploy undercloud VM
  command: /usr/bin/virt-install --ram {{ hostvars['osp10-undercloud'].mem }} --vcpus {{ hostvars['osp10-undercloud'].cpu }} --os-variant {{ hostvars['osp10-undercloud'].os.variant }} --disk path={{ hostvars['osp10-undercloud'].disk.path }}/{{ hostvars['osp10-undercloud'].undercloud_name }}.qcow2,device=disk,bus=virtio,format=qcow2 --import --noautoconsole --vnc --network network:provisioning --network network:default --name {{ hostvars['osp10-undercloud'].undercloud_name }}
  when: ("osp10-undercloud" not in "{{ virt_vms.list_vms }}")

# Pause the deployment
- name: Pause the deployment
  pause: minutes=1
  when: ("osp10-undercloud" not in "{{ virt_vms.list_vms }}")

######################################
#
#  Now let's create the overcloud VMs
#

- name: Create overcloud VMs without storage
  include: create_overcloudVMs.yml
  with_items: "{{ groups[overcloudnodes] }}"
  when: (item not in virt_vms.list_vms)
