---
- name: Get Instance list
  shell: >
    . ~/overcloudrc &&
    nova list
  register: images
  changed_when: false

- block:
  - name: Create instance
    shell: >
      . ~/overcloudrc &&
      internal_net=$(neutron net-list | awk ' /internal/ {print $2;}') &&
      nova boot --flavor m1.tiny --nic net-id=$internal_net \
      --image cirros overcloud-test 
    
  - name: Adding the floating IPs
    shell: . ~/overcloudrc && neutron floatingip-create management | awk ' /floating_ip_address/ {print $4;}'
    register: floatingip 
    
  - name: Associate network IP to the project {{ time }}
    shell: >
      . ~/overcloudrc &&
      nova add-floating-ip overcloud-test {{ floatingip.stdout }}
  when: '"overcloud-test" not in images.stdout'

