# Image
image_path: /var/lib/libvirt/images/
image_rhel7_guest: 'rhel73-guest.qcow2'
image_rhel7_orign: "rhel-guest-image-7.3-36.x86_64.qcow2"
image_size: 1280311296
image_full_path: /var/lib/libvirt/images/rhel73-guest.qcow2
rhel_guest_url: "http://download-node-02.eng.bos.redhat.com/brewroot/packages/rhel-guest-image/7.3/36/images/rhel-guest-image-7.3-36.x86_64.qcow2" 

