---
#- name: import secret variable file
#  include_vars: "secret.yml"
#  no_log: true

- name: Get external ouvercloud route
  shell: sudo ip route show |grep "172.17.1.0"|wc -l
  register: findroute
  ignore_errors: True

- name: add default route to the external overcloud network
  shell: sudo ip route add 172.17.1.0/24 via 172.16.0.1
  when: findroute is not defined or findroute.stdout == "0"


- name: Deploy the overcloud without CEPH
  shell: >
    . ~/stackrc && {{ lookup('template','deployovercloud.j2') }} 
  when: '"ceph" not in "{{ overcloudnodes }}"'


- name: Deploy the overcloud WITH ceph
  shell: >
    . ~/stackrc && {{ lookup('template','deployovercloud_withceph.j2') }} 
  when: '"ceph" in "{{ overcloudnodes }}"'
